config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :articles do
    resources :comments
  end

  get 'signin', to: 'sessions#new'
  post 'signin', to: 'sessions#create'
  delete 'signout', to: 'sessions#destroy'
  post '/articles/:article_id/likes', to: 'likes#like' , as: 'likes' 
  post '/articles/:article_id/dislikes', to: 'likes#dislike', as: 'dislikes'

  root 'home#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :title, presence: true, length: { minimum: 3, maximum: 30 }
  validates :text, presence: true, length: { minimum: 5, maximum: 60 }
  validates :user_id, presence: true
  
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :article

  validates :text, presence: true, length: { minimum: 5, maximum: 60 }
  validates :article_id, presence: true
  
end

app/models/user.rb
class User < ApplicationRecord

  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

    validates :email, presence: true, uniqueness:true,
    format: { with: VALID_EMAIL_REGEX }
    
    validates :password, confirmation: { case_sensitive: true }

    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?, :current_article

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in first "
      redirect_to root_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 3).order(created_at: :desc)
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy

    redirect_to articles_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :text)
  end

  def set_article
    @article = Article.find(params[:id])
  end

  def require_same_user
    if current_user != @article.user
      flash[:danger] = "you can only perform these action on your own articles"
      redirect_to root_path
    end
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :set_comment, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index]

  def new
  end

  def edit
  end
  
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    @comment.user = current_user
    @comment.save
    redirect_to article_path(@article)
  end

  def update
    @comment.update(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
		@comment.destroy
		redirect_to article_path(@article)
	end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end

  def set_article
    @article = Article.find(params[:article_id])
  end

  def set_comment
    @comment = @article.comments.find(params[:id])
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def new
  end

  def home
    redirect_to articles_path if logged_in?
  end

  def create
  end
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :require_user
  before_action :find_article, :count_like, :count_dislike

  def like
    if 
      flash[:notice] = "You can't like more than once"
    else
      @article.like = @total_like + 1
      @article.save
    end
    redirect_to article_path(@article)
  end

  def dislike
    if 
      flash[:notice] = "Cannot unlike"
    else
      @article.dislike = @total_dislike + 1
      @article.save
    end
    redirect_to article_path(@article)
  end


  private

  def find_article
    @article = Article.find(params[:article_id])
  end

  def count_like
    @total_like = @article.like
  end

  def count_dislike
    @total_dislike = @article.dislike
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to '/articles'
    else
      flash[:alert] = "User not found! "
      redirect_to '/signin'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "you have logged out "
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def index
    @user = User.paginate(page:params[:page], per_page: 3)
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "successfully created! "
      redirect_to articles_path
    else
      flash[:alert] = "fill all the details correctly! "
      redirect_to new_user_path
    end
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.first_name, class: "img-circle")
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/articles/_form.html.erb
<%= bootstrap_form_with model: @article, local: true do |form| %>

  <div class = "well">
    <%= form.text_field :title %>

    <%= form.text_area :text %>

    <%= form.submit %>
  </div>
 
<% end %>

app/views/articles/edit.html.erb
<div class = "page-header">
  Edit Article 
</div>
 
<%= render 'form' %>
 
<div class = "btn-div">
  <%= link_to 'Back', articles_path, :class => "btn btn-default btn-lg" %>
</div>

app/views/articles/index.html.erb
<div class = "page-header">
  
</div>
<% if current_user %>
<div class="col-sm-3">
  <div class="row-1">
    <div class="card text-center gravatar">
      <%= gravatar_for current_user, size: 80 %>
    </div>
    <div class="card text-center">
      <li><%= current_user.first_name.capitalize+" "+current_user.last_name.capitalize %></li>
      <li><%= current_user.email %></li>
      <li><%= "Join at : #{current_user.created_at.strftime("%d/%m/%Y")}" %></li>
      <li><%= "Article : #{current_user.articles.count}" %></li>
    </div>
  </div>
  <div class="row-2">
    <div class="card text-center">
      <li><%= current_user.first_name %></li>
      <li><%= current_user.first_name %></li>
      <li><%= current_user.first_name %></li>
      <li><%= current_user.first_name %></li>
      <li><%= current_user.first_name %></li>
      <li><%= current_user.first_name %></li>
    </div>
  </div>
</div>
<% end %>
<div class="col-sm-6">
    <div class="card text-center">
      <div class="card-header">
      <% if logged_in? %>
        <% name = current_user.first_name %>
        <h2> Welcome <%= name.capitalize! %> </h2>
      <% end %>
      </div>
    <%= will_paginate @articles, :id => 'page_scroll'%>
        <% @articles.each do |article| %>
          <div class = "well" , id = "well-article" >
            <div class="card-body">
            <h3 class="card-title">Title: <%= article.title %></h3>
            <p class="card-text">Descriptions: <%= article.text %></p>
            <p> Created by: <%= article.user.first_name.capitalize %>, <%= article.created_at.strftime("%d/%m/%Y") %></p>
            <%= link_to 'Show', article_path(article), class: "btn btn-primary" %>
          <% if article.user == current_user %>
            <%= link_to 'Edit', edit_article_path(article), class: "btn btn-info" %>
            <%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
          <% end %>
            </div>
          </div>          
          <% end %>
    <%=will_paginate @articles, :id => 'page_scroll'%>
      <div class="card-footer text-muted">
        <% if logged_in? %>
          <%= link_to 'New article', new_article_path, :class => "btn btn-default " %>
          <%= link_to 'Log out', signout_path, method: :delete, :class => "btn btn-default" %>
        <% end %>
          <%= link_to 'Back', root_path, :class => "btn btn-default " %>
      </div>
    </div>
</div>
<div class="col-sm-3">
  
</div>

app/views/articles/new.html.erb
<div class = "page-header">
  New Article 
</div>

<%= render 'form' %>

<div class = "btn-div">
  <%= link_to 'back', articles_path, :class => "btn btn-default btn-lg" %>
</div>

app/views/articles/show.html.erb
<div class = "page-header">
  Showing Articles
</div>
    <div class="card text-center">
      <div class = "well">
        <div class="card-body">
          <h3 class="card-title">Title: <b><%= @article.title %></b></h3>
          <p class="card-text">Descriptions: <%= @article.text %></p>
          <%= @article.like %>
          <%= link_to raw('<span class="glyphicon glyphicon-thumbs-up"></span>'),likes_path(@article), method: :post, class: "btn btn-link btn-lg" %>
          <%= link_to raw('<span class="glyphicon glyphicon-thumbs-down"></span>'),dislikes_path(@article), method: :post, class: "btn btn-link btn-lg" %>
          <%= @article.dislike %>  
          <hr>
          <p class = "text-left"> <b> Leave a comment: </b> </p>
          <%= render @article.comments %>
          <%= render 'comments/form' %>
        </div>
      </div>
      <div class="card-footer text-muted">
        <% if @article.user == current_user %>
          <%= link_to 'Edit', edit_article_path(@article), :class => "btn btn-info" %>
        <% end %>
          <%= link_to 'Back', articles_path, :class => "btn btn-default" %>
      </div>
    </div>

app/views/comments/_comment.html.erb
<div class="card text-left">
    <div class="card-body">
      <div>
        <li><b><%= comment.text %></b> 
        by:<%= comment.user.first_name.capitalize! %>
        <% if comment.user == current_user || comment.article.user == current_user %>
          <div class="del-icon">
            <%= link_to raw('<span class="glyphicon glyphicon-pencil"></span>'),edit_article_comment_path(comment.article,comment), class: "btn btn-link" %>
            <%= link_to raw('<span class="glyphicon glyphicon-remove"></span>'), article_comment_path(comment.article,comment), method: :delete, 
            class: "btn btn-link", data: { confirm: 'Are you sure?' } %>
          </div> 
        <% end %> 
        </li>
      </div>
    </div>
</div>

app/views/comments/_form.html.erb
<%= bootstrap_form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
  <%= form.text_area :text, label:"Comment" %>
  <%= form.submit "comment" %>
<% end %>

app/views/comments/edit.html.erb
<div class = "page-header">
  Edit Comment
</div>
<div class="card text-center">
  <div class = "well">
    <div class="card-body">
      <%= bootstrap_form_with(model: [ @article, @comment ], local: true) do |form| %>
        <%= form.text_area :text, label:"Edit comment" %>
        <%= form.submit "comment" %>
      <% end %>
    </div>
  </div>
</div>

app/views/home/home.html.erb
<div class = "page-header">
  Welcome to Niche blogging
</div>
<div class = "btn-div">
  <div>
    <%= link_to 'LogIn', signin_path , :class => "btn btn-default btn-lg" %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<section id="lab_social_icon_footer">
<!-- Include Font Awesome Stylesheet in Header -->
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <div class="container">
        <div class="text-center center-block">
          <a href="#"><i id="social-fb" class="fa fa-facebook-square fa-3x social"></i></a>
          <a href="#"><i id="social-tw" class="fa fa-twitter-square fa-3x social"></i></a>
          <a href="#"><i id="social-gp" class="fa fa-google-plus-square fa-3x social"></i></a>
          <a href="#"><i id="social-em" class="fa fa-envelope-square fa-3x social"></i></a>
        </div>
    </div>
  <div class="footer-copyright text-center py-3">
      <a href="#">© 2020 Copyright: ADITYA </a>
  </div>
</section>

app/views/layouts/_navbar.html.erb
<%# <div class="jumbotron text-center">
  <h1>Niche Blog</h1>
  <p>We deal in small content</p>
</div> %>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <%# <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> %>
      </button>
      <%= link_to "Niche Blog", root_path, class:"navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li> <%= link_to "Home", root_path %> </li>
        <li> <%= link_to "Article", articles_path %></li>
        <li> <%= link_to "User", users_path %></li>
        <% if !logged_in? %>
          <li> <a href="/users/new"><span class="glyphicon glyphicon-user"></span> Sign Up</a> </li>
          <li> <a href="/signin"><span class="glyphicon glyphicon-log-in"></span> Login</a> </li>
        <% else %>
          <li> <a href="#"><span class="glyphicon glyphicon-user"></span> <%= current_user.first_name.capitalize %></a> </li>
          <li> <%= link_to "Logout", signout_path, method: :delete %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BasicApp</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="well-collapse">
      <% flash.each do |type, msg| %>
        <div>
          <%= msg %>
        </div>
      <% end %>
    </div>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/users/index.html.erb
<div class = "page-header">
  Listing Users
</div>
<div class="card text-center">
<%= will_paginate @user, :id => 'page_scroll'%>
  <div class = "well">
    <div class="card-body">
      <% @user.each do |user| %>
        <h3 class="card-title">Name: <%= user.first_name.capitalize+" "+ user.last_name %></h3>
        <p class="card-text">Email: <%= user.email %></p>
        <p> Articles count:  <%= user.articles.count %></p>
        <p> Comments count:  <%= user.comments.count %></p>
        <hr>
      <% end %>
    </div>
  </div>
<%= will_paginate @user, :id => 'page_scroll'%>

  <div class="card-footer text-muted">
    <%= link_to 'SignUp', new_user_path, :class => "btn btn-default" %>
    <%= link_to 'back', root_path, :class => "btn btn-default " %>
  </div>

</div>

app/views/users/new.html.erb
<div class = "page-header">
  SignUp
</div>
<div class = "form">
  <div class = "well">
    <%= bootstrap_form_for :user, url:users_path, class: "signupForm" do |f| %>
      <%= f.text_field :first_name %>
      <%= f.text_field :last_name %>
      <%= f.text_field :email %>
      <%= f.password_field :password %>
      <%= f.password_field :password_confirmation %> 
      <%= f.submit "Create account", :class => "btn btn-default" %></p>
    <% end %>
  </div>
</div>
<div class="card text-center">
  <div class="card-footer text-muted">
    <%= link_to 'Back', root_path, :class => "btn btn-default " %>
  </div>
</div>

app/views/users/signup.html.erb
<h1> SignUp page </h1>

<%= form_for :user, url:users_path, class: "signupForm" do |f| %>

  <p>
  <%= f.label :first_name %></p>
  <p><%= f.text_field :first_name, class: "shortInput" %> </p>

  <p>
  <%= f.label :last_name %></p>
  <p><%= f.text_field :last_name, class: "shortInput" %> </p>

  <p>
  <%= f.label :email, "Email Address" %></p>
  <p><%= f.text_field :email, class: "shortInput" %> </p>

  <p>
  <%= f.label :password %></p>
  <p><%= f.password_field :password, class: "shortInput" %> </p>

  <p>
  <%= f.label :password_confirmation, "Confirm Password" %></p>
  <p><%= f.password_field :password_confirmation, class: "shortInput" %> </p>

  <p>
  <%= f.submit "Create account", class: "button createAccount" %></p>

<% end %>